language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --use-mirrors  # TODO: put these deps in tests_require
  - pip install pytest-cov
  - pip install coverage
# command to run tests
script:
  python setup.py develop
  py.test --cov=mockextras --cov-report=term --verbose
after_success:
  coveralls --verbose
