language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py develop
# command to run tests
script:
  py.test --cov=mockextras --cov-report=term --verbose
after_success:
  coveralls --verbose
